### ISSUE TITLE
config_file_options_hash does not work?

### ISSUE THREAD

**Issue by slyoldfox** [dhoppe/puppet-fail2ban#10]
I have the following config:
class { 'fail2ban':
  config_file_template => "fail2ban/${::lsbdistcodename}/etc/fail2ban/jail.conf.erb",
  config_file_options_hash => {
    '::fail2ban:whitelist' => '127.0.0.1/8 192.168.2.0/23',
  },
}
However config_file_options_hash is not applied.
On first sight there aren't any code paths that handles this variable at all?

https://github.com/dhoppe/puppet-fail2ban/search?utf8=%E2%9C%93&q=config_file_options_hash

**Comment by mnellemann** [comment]
Hi,

I am also trying to use **config_file_options_hash** w. hiera, to enable syslogging without luck.

    fail2ban::config_file_options_hash:
      'logtarget': 'SYSLOG'

Could be related or perhaps I'm not doing it right?

**Comment by mnellemann** [comment]
@slyoldfox 

I don't think you need to use **config_file_options_hash** to specify your whitelist.

I'm doing the following in hiera which works fine:

    fail2ban::whitelist:
      - '127.0.0.1/8'
      - '192.168.20.0/24'
      - '172.16.1.0/24'
      - '10.0.0.0/8'

Ends up as ```ignoreip = 127.0.0.1/8 192.168.20.0/24 172.16.1.0/24 10.0.0.0/8``` in **jail.conf**.

**Comment by dhoppe** [comment]
@slyoldfox @mnellemann The parameter ```config_file_options_hash``` should be used, if you use your own template and want to provide config parameters which the module did not know about.
