### ISSUE TITLE
Issue with Vivid Vervet

### ISSUE THREAD

**Issue by nicocube** [dhoppe/puppet-fail2ban#11]
Hi,

I tryed to use your puppet module on an Ubuntu 15.04, AKA Vivid Vervet, and so `${::lsbdistcodename}` resolve to "vivid" in my config : 

      class { fail2ban:
        config_file_template => "fail2ban/${::lsbdistcodename}/etc/fail2ban/jail.conf.erb",
        bantime   => 3600,
        email     => "",
        whitelist => $whitelisted_hosts,
      }

I get this error message :

    Error: Could not find template 'fail2ban/vivid/etc/fail2ban/jail.conf.erb' at /etc/puppet/modules/fail2ban/manifests/init.pp:65 on node ...

As templates folder https://github.com/dhoppe/puppet-fail2ban/tree/master/templates does not contains a *vivid* subfolder I can tell why I get this error, but starting there, as I am new to puppet, I do not know what to do. :(

Is there any way to fix that?

**Comment by dhoppe** [comment]
@nicocube There is no template for Ubuntu 15.04 because this is no LTS release. But you can create your own template and use this by modifying the parameter ```config_file_template```.
